name: myapp
description: A exported flutter project from FUNCTION12


# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  intl: ^0.17.0
  timeline_tile: ^2.0.0
  webview_flutter: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/page-1/images/1home.png
    - assets/page-1/images/auto-group-q3an.png
    - assets/page-1/images/add-image-1.png
    - assets/page-1/images/polygon-13.png
    - assets/page-1/images/ellipse-26-bg.png
    - assets/page-1/images/whatsapp-image-2023-04-26-at-556-2-bg.png
    - assets/page-1/images/mask-group.png
    - assets/page-1/images/.png
    - assets/page-1/images/add-image-1-iSr.png
    - assets/page-1/images/headset-5.png
    - assets/page-1/images/video-button-1.png
    - assets/page-1/images/mask-group-jcA.png
    - assets/page-1/images/keyboard-parts-keys-icon-shift.png
    - assets/page-1/images/ellipse-26-bg-mLA.png
    - assets/page-1/images/keyboard-parts-keys-icon-backspace.png
    - assets/page-1/images/menu-1.png
    - assets/page-1/images/arrow-down-sign-to-navigate-1.png
    - assets/page-1/images/accept-1.png
    - assets/page-1/images/google-docs-1.png
    - assets/page-1/images/ellipse-26-bg-mLa.png
    - assets/page-1/images/whatsapp-image-2023-04-26-at-556-3-bg.png
    - assets/page-1/images/arrow-down-sign-to-navigate-1-mmY.png
    - assets/page-1/images/edit-4.png
    - assets/page-1/images/whatsapp-image-2023-04-26-at-556-5-bg.png
    - assets/page-1/images/menu-1-xFp.png
    - assets/page-1/images/arrow-down-sign-to-navigate-1-pbG.png
    - assets/page-1/images/complaint-1-1.png
    - assets/page-1/images/ellipse-26-bg-xqk.png
    - assets/page-1/images/complaint-1-1-KKU.png
    - assets/page-1/images/vector.png
    - assets/page-1/images/auto-group-qrev.png
    - assets/page-1/images/headset-5-yEn.png
    - assets/page-1/images/vector-7Vx.png
    - assets/page-1/images/google-docs-1-c7g.png
    - assets/page-1/images/auto-group-2ypk.png
    - assets/page-1/images/video-button-1-kpe.png
    - assets/page-1/images/edit-1.png
    - assets/page-1/images/ellipse-26-bg-DZ8.png
    - assets/page-1/images/video-button-1-Hj4.png
    - assets/page-1/images/ellipse-26-bg-srn.png
    - assets/page-1/images/edit-3.png
    - assets/page-1/images/vector-Rx2.png
    - assets/page-1/images/vector-kUW.png
    - assets/page-1/images/arrow-down-sign-to-navigate-1-CXY.png
    - assets/page-1/images/video-button-1-YMk.png
    - assets/page-1/images/ellipse-28-bg.png
    - assets/page-1/images/google-docs-1-rCe.png
    - assets/page-1/images/ellipse-28-bg-SrJ.png
    - assets/page-1/images/whatsapp-image-2023-04-26-at-556-6-bg.png
    - assets/page-1/images/keyboard-parts-keys-icon-backspace-w2v.png
    - assets/page-1/images/user-1.png
    - assets/page-1/images/vector-2Ge.png
    - assets/page-1/images/vector-mJ6.png
    - assets/page-1/images/ellipse-28-bg-kdC.png
    - assets/page-1/images/vector-chL.png
    - assets/page-1/images/auto-group-wusj.png
    - assets/page-1/images/vector-BY2.png
    - assets/page-1/images/vector-jan.png
    - assets/page-1/images/auto-group-pcvz.png
    - assets/page-1/images/ellipse-26-bg-WNS.png
    - assets/page-1/images/facebook-1.png
    - assets/page-1/images/edit-2.png
    - assets/page-1/images/history-1.png
    - assets/page-1/images/vector-wFC.png
    - assets/page-1/images/vector-8sQ.png
    - assets/page-1/images/history-1-s4J.png
    - assets/page-1/images/polygon-12.png
    - assets/page-1/images/paper-1.png
    - assets/page-1/images/polygon-10.png
    - assets/page-1/images/instagram.png
    - assets/page-1/images/add-image-1-mHQ.png
    - assets/page-1/images/paper-1-RPt.png
    - assets/page-1/images/auto-group-2trn.png
    - assets/page-1/images/headset-5-a9C.png
    - assets/page-1/images/whatsapp-image-2023-04-26-at-556-4-bg.png
    - assets/page-1/images/support-1.png
    - assets/page-1/images/support-1-fYr.png
    - assets/page-1/images/polygon-9.png
    - assets/page-1/images/vector-kAa.png
    - assets/page-1/images/googleglogo-1.png
    - assets/page-1/images/ellipse-40.png
    - assets/page-1/images/keyboard-parts-keys-icon-shift-U5t.png
    - assets/page-1/images/add-image-1-eVU.png
    - assets/page-1/images/vector-7iv.png
    - assets/page-1/images/auto-group-bwvy.png
    - assets/page-1/images/auto-group-hsou.png
    - assets/page-1/images/auto-group-utjz.png
    - assets/page-1/images/tracking-1.png
    - assets/page-1/images/group-6.png
    - assets/page-1/images/expresso-1.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
